<h1>Introduction to Tensors</h1>

In [1]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.5.0


In [2]:
# Create tensors with tf.constant()
scalar=tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# check the no of dimensions of a tensor (ndim)
scalar.ndim

0

In [4]:
# create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [5]:
vector.ndim

1

In [6]:
# create a matrix (has more than 1 dimension)
matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [7]:
matrix.ndim

2

In [8]:
#create another matrix
another_matrix=tf.constant([[10.,7.],[3.,2.],[8.,9.]], dtype=tf.float16) # specify the data type with dtype operator
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [9]:
#whats the no dimensions of another_atrix?
another_matrix.ndim

2

In [10]:
#Lets create a tensor
tensor = tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])>

In [11]:
tensor.ndim

3

In [12]:
# Creating Tensor using tf.Variable
tf.Variable

changeable_tensor=tf.Variable([10,7])
unchangeable_tensor=tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

#Lets try to chnage changeable tensor changeable_tensor [0] = 7 changeable_tensor


In [13]:
# How about we try .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7])>

#Lets try to change unchangable tensor
unchangeable_tensor[0].assign(7)
unchangeable_tensor

<h3>Creating Random Tensors</h3>
Random Tensors - some arbitary size which contain random nos.

In [14]:
# create 2 random tensors (but the same) tensors
random_1=tf.random.Generator.from_seed(42) #seed - reproductibility
random_1=random_1.normal(shape=(3,2))
random_2=tf.random.Generator.from_seed(42)
random_2=random_2.normal(shape=(3,2))

# Are they equal?
random_1, random_2, random_1==random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

<h3>Shuffle the order of elements in a tensor</h3>

In [15]:
# Shuffle a tensor (valuable for when you want to shuffle your data so the inherent)

not_shuffled=tf.constant([[10,7],[3,4],[2,5]])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]])>

In [16]:
# Shuffle non-shuffled
shuffled__non_shuffled=tf.random.shuffle(not_shuffled)
shuffled__non_shuffled 

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]])>

In [17]:
# Shuffle non-shuffled with seed (gloabal n operational)
tf.random.set_seed(42)
shuffled__non_shuffled=tf.random.shuffle(not_shuffled, seed=42)
shuffled__non_shuffled 

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]])>

In [18]:
# create a tensor of all ones
ones=tf.ones([10,7])
ones

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [19]:
tf.shape(ones),ones.ndim

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>, 2)

In [20]:
# create a tensor of all zeroes
zeros=tf.zeros(shape=(3,4))
zeros

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [21]:
zeros.shape,zeros.ndim

(TensorShape([3, 4]), 2)

In [22]:
# you can also turn numpy arrays into tensors
#tensors - gpu (faster)
import numpy as np 
numpy_A=np.arange(1,25, dtype=np.int32) # b/w 1 n 25
numpy_A

# x = tf.constant(some_matrix) # capital for matrix or tensor
# y = tf.constant(vector) # non-capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [23]:
A=tf.constant(numpy_A,shape=(3,8))
B=tf.constant(numpy_A)
A,A.shape

(<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
 array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24]])>,
 TensorShape([3, 8]))

In [24]:
cd=np.zeros(shape=(3,8))
cd,cd.dtype

(array([[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]]),
 dtype('float64'))

<h3>Getting info from tensors</h3>

In [25]:
#Shape, Rank, Axis/Dimension, Size

# create a rank 4 tensor (4d)

rank_4_tensor=tf.zeros(shape=(2,3,4,5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [26]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [27]:
rank_4_tensor.ndim, rank_4_tensor.shape, tf.size(rank_4_tensor)

(4, TensorShape([2, 3, 4, 5]), <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [28]:
# Get various attributes of out tensors
print("Datatype of every element : ",rank_4_tensor.dtype)
print("Number of dimensions (rank) : ", rank_4_tensor.ndim)
print("Shape of tensor : ", rank_4_tensor.shape)
print("Elements along the 0-axis : ", rank_4_tensor.shape[0])
print("Elements along the last-axis : ", rank_4_tensor.shape[-1])
print("Total no of elements in our tensor : ", tf.size(rank_4_tensor))
print("Total no of elements in our tensor (numpy): ", tf.size(rank_4_tensor).numpy())

Datatype of every element :  <dtype: 'float32'>
Number of dimensions (rank) :  4
Shape of tensor :  (2, 3, 4, 5)
Elements along the 0-axis :  2
Elements along the last-axis :  5
Total no of elements in our tensor :  tf.Tensor(120, shape=(), dtype=int32)
Total no of elements in our tensor (numpy):  120


<h3>Indexing tensors</h3>

In [29]:
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [30]:
rank_4_tensor1=tf.zeros(shape=(2,2,2,2))
rank_4_tensor1

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [31]:
# get the first 2 elements of each dimension
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [32]:
# get the first element from each dimension from each index except for the final one
# TensorShape[2,3,4,5]
rank_4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [33]:
# create a rank 2 tensor
rank_2_tensor=tf.constant([[10,7],[3,4]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [34]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [35]:
# get the last item from each of row of our rank 2 tensor

rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4])>

In [36]:
# add a new axis to our rank 2 tensor

rank_3_tensor=rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]])>

In [37]:
# alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis =-1)


<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]])>

In [38]:
# expand the 0-axis
tf.expand_dims(rank_2_tensor,axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]])>

<h3>Manipulating tensors / operations on tensors</h3>

In [39]:
# basic operations + - * /

#you can add values to a tensor using the addition operator

tensor=tf.constant([[10,7],[3,4]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [40]:
#addition
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]])>

In [41]:
# original tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [42]:
#multiplication
tensor*3

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[30, 21],
       [ 9, 12]])>

In [43]:
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]])>

In [44]:
tf.math.add(tensor,3)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[13, 10],
       [ 6,  7]])>

In [45]:
tensor-5

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5,  2],
       [-2, -1]])>

<h3>Matrix multiplication</h3>
matrix multiplication is most common in tensors

In [46]:
print(tensor)
tf.matmul(tensor,tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

In [47]:
tensor,tensor

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]])>)

In [48]:
tensor*tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]])>

In [49]:
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

In [50]:
tensor.shape

TensorShape([2, 2])

In [51]:
# create  a tensor (3,2)
x=tf.constant([[1,2],[3,4],[5,6]])
y=tf.constant([[7,8],[9,10],[11,12]])
x,y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]])>)

tf.matmul(x,y)

In [52]:
p=tf.constant([[1,2],[3,4],[5,6]])
q=tf.constant([[7,8],[9,10]])
p,q

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10]])>)

In [53]:
p @ q

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 25,  28],
       [ 57,  64],
       [ 89, 100]])>

In [54]:
y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7,  8],
       [ 9, 10],
       [11, 12]])>

In [55]:
# lets change the shape of y
reshaped_y=tf.reshape(y,shape=(2,3))
y,reshaped_y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]])>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7,  8,  9],
        [10, 11, 12]])>)

In [56]:
x.shape, reshaped_y.shape

(TensorShape([3, 2]), TensorShape([2, 3]))

In [57]:
#try to matrix multiply x by reshaped y
tf.matmul(x,reshaped_y)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]])>

In [58]:
# lets change the shape of x
reshaped_x=tf.reshape(x,shape=(2,3))
x,reshaped_x

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]])>)

In [59]:
tf.matmul(reshaped_x,y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]])>

In [60]:
# can do the same with transpose
transp_x=tf.transpose(x)
x.shape,reshaped_x.shape, transp_x.shape

(TensorShape([3, 2]), TensorShape([2, 3]), TensorShape([2, 3]))

In [61]:
x,transp_x,reshaped_x

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]])>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]])>)

In [62]:
tf.matmul(reshaped_x,y), tf.matmul(transp_x,y)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 58,  64],
        [139, 154]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 89,  98],
        [116, 128]])>)

In [63]:
# perform the dot product on x and y (requires x or y to be transposed)
tf.tensordot(transp_x,y,axes=1)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]])>

In [64]:
transp_y=tf.transpose(y)
transp_y

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  9, 11],
       [ 8, 10, 12]])>

In [65]:
#perform matrix multiplication b/w  x and y (transposed)
tf.matmul(x,transp_y)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]])>

In [66]:
#perform matrix multiplication b/w x and y (reshaped)
tf.matmul(x,reshaped_y)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]])>

In [67]:
# check the values of y, reshaped y, transposed y
print("Normal Y : ")
print(y,"\n")
print("Reshaped Y : ")
print(reshaped_y,"\n")
print("Transposed Y : ")
print(transp_y,"\n")

Normal Y : 
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Reshaped Y : 
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Transposed Y : 
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32) 



<h3>Changing the datatype of tensor</h3>

In [68]:
# create a new tensor with the default dt (float32)

C=tf.constant([1.7,7.4])
C.dtype

tf.float32

In [69]:
D=tf.constant([7,4])
D.dtype

tf.int32

In [70]:
 #change from f32 - f16 (reduced precision)
 E=tf.cast(C,dtype=tf.float16)
 E,E.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

In [71]:
F=tf.cast(D,dtype=tf.float32)
F

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([7., 4.], dtype=float32)>

In [72]:
F_float16=tf.cast(F,dtype=tf.float16)
F_float16

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([7., 4.], dtype=float16)>

<h3>Aggregating Tensors</h3>
-min,max,mean,sum

In [73]:
E=tf.constant([-7,-10])
E

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10])>

In [74]:
#get the absolute values
tf.abs(E)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10])>

In [75]:
# creating a random tensor with values b/w 0 and 100 of size 50
G=tf.constant(np.random.randint(0,100,size=50))
G

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([57, 84, 97, 43, 54, 27, 81, 31, 35, 47,  3, 19, 74, 33, 75, 42, 72,
       86,  6, 68, 43, 77, 56, 90, 65, 41, 56, 52, 21, 56, 73,  1, 69, 27,
       91, 15,  5, 61, 70, 56, 47, 51, 68, 77, 16, 32, 23, 78, 37, 31])>

In [76]:
tf.size(G),G.ndim,G.shape

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, 1, TensorShape([50]))

In [77]:
#min, max, mean, sum

print("Min : ",tf.reduce_min(G).numpy())
print("Max : ",tf.reduce_max(G).numpy())
print("Mean : ",tf.reduce_mean(G).numpy())
print("Sum : ",tf.reduce_sum(G).numpy())

Min :  1
Max :  97
Mean :  50
Sum :  2519


In [78]:
#variance - need tf_probability package
import tensorflow_probability as tfp 
tfp.stats.variance(G).numpy()

637

In [79]:
tf.math.reduce_std(tf.cast(G, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=25.239565>

<h3>Find the positional max n min</h3>

In [80]:
tf.random.set_seed(42)
H = tf.random.uniform(shape=[50])
H

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [81]:
# postitional max
tf.argmax(H)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [82]:
# index on our largest value pos
H[tf.argmax(H)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [83]:
#max value of H
tf.reduce_max(H)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [84]:
#check for equality
H[tf.argmax(H)]==tf.reduce_max(H)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [85]:
#positional min
tf.argmin(H)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [86]:
H[tf.argmin(H)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

<h3>Squeezing a tensor (removing all 1Ds / reducing)</h3>

In [87]:
tf.random.set_seed(42)
I=tf.constant(tf.random.normal(shape=[50]),shape=(1,1,1,50))
I

<tf.Tensor: shape=(1, 1, 1, 50), dtype=float32, numpy=
array([[[[ 0.3274685 , -0.8426258 ,  0.3194337 , -1.4075519 ,
          -2.3880599 , -1.0392479 , -0.5573232 ,  0.539707  ,
           1.6994323 ,  0.28893656, -1.5066116 , -0.2645474 ,
          -0.59722406, -1.9171132 , -0.62044144,  0.8504023 ,
          -0.40604794, -3.0258412 ,  0.9058464 ,  0.29855987,
          -0.22561555, -0.7616443 , -1.8917141 , -0.93847126,
           0.77852213, -0.47338897,  0.97772694,  0.24694404,
           0.20573747, -0.5256233 ,  0.32410017,  0.02545409,
          -0.10638497, -0.6369475 ,  1.1603122 ,  0.2507359 ,
          -0.41728503,  0.4012578 , -1.4145443 , -0.5931857 ,
          -1.6617213 ,  0.33567193,  0.10815629,  0.23479682,
          -0.56668764, -0.35819843,  0.88698614,  0.52744764,
           0.70402247, -0.33421248]]]], dtype=float32)>

In [88]:
tf.squeeze(I)

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([ 0.3274685 , -0.8426258 ,  0.3194337 , -1.4075519 , -2.3880599 ,
       -1.0392479 , -0.5573232 ,  0.539707  ,  1.6994323 ,  0.28893656,
       -1.5066116 , -0.2645474 , -0.59722406, -1.9171132 , -0.62044144,
        0.8504023 , -0.40604794, -3.0258412 ,  0.9058464 ,  0.29855987,
       -0.22561555, -0.7616443 , -1.8917141 , -0.93847126,  0.77852213,
       -0.47338897,  0.97772694,  0.24694404,  0.20573747, -0.5256233 ,
        0.32410017,  0.02545409, -0.10638497, -0.6369475 ,  1.1603122 ,
        0.2507359 , -0.41728503,  0.4012578 , -1.4145443 , -0.5931857 ,
       -1.6617213 ,  0.33567193,  0.10815629,  0.23479682, -0.56668764,
       -0.35819843,  0.88698614,  0.52744764,  0.70402247, -0.33421248],
      dtype=float32)>

In [89]:
tf.squeeze(I).ndim,I.ndim

(1, 4)

<h3>One - Hot Encoding Tensors</h3>

In [90]:
#create a list of indicies
some_list=[0,1,2,3] #red,green,blue,yellow

#one-hot encoding
tf.one_hot(some_list,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [91]:
#specify custom values for one-hot encoding
tf.one_hot(some_list,depth=4,on_value="AB",off_value="CD")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'AB', b'CD', b'CD', b'CD'],
       [b'CD', b'AB', b'CD', b'CD'],
       [b'CD', b'CD', b'AB', b'CD'],
       [b'CD', b'CD', b'CD', b'AB']], dtype=object)>

<h3>Squaring, Log, Square</h3>

<h3>Tensors and Numpy</h3>

In [92]:
#create a tensor directly from a Numpy arrays

J=tf.constant(np.array([3.,5.,8.,15.]))
J

<tf.Tensor: shape=(4,), dtype=float64, numpy=array([ 3.,  5.,  8., 15.])>

In [93]:
#convert tensor back to Numpy
np.array(J), type(np.array(J))

(array([ 3.,  5.,  8., 15.]), numpy.ndarray)

In [94]:
#convert tensor J back to Numpy
J.numpy(),type(J.numpy())

(array([ 3.,  5.,  8., 15.]), numpy.ndarray)